name: Deploy to Fly
on: workflow_dispatch
env:
  FLY_API_TOKEN: "fo1_DKKgH-35UXmAFJxAVumhuSyVu49c38zSxz6c-k7d9sI"
jobs:
  deploy:
      name: Deploy to Fly
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: |
            sed -i 's#APP-NAME#${{secrets.APP_NAME}}#' fly.toml
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl launch --generate-name --copy-config --region lax --no-deploy
        - run: flyctl deploy --remote-only
